#
# Config file for Jekyll
#

# Change timezone to London
timezone: Europe/London

# Remove dates from permalinks
permalink: title

# Define URL for sitemap and SEO
url: "https://christopherporter.co.uk"

# Keep this files out of the built site
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Minify compiled SASS
sass:
  style: compressed

# Add any plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
